FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/internetShop

COPY ./requirements.txt /usr/src/requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r /usr/src/requirements.txt

COPY . /usr/src/internetShop